---
title: "Junxian Chen"
output: 
  html_document:
    toc: true
    toc_float: true
---

<br/>

## Education

*May 2021*, Columbia University, Mailman School of Public Health, NY, US

**Master of Science in Biostatistics**, *theory and method track*


**Selected Courses**: Data Science, Machine Learning, Computer System, Probability, Inference, Biostatistical Methods I&II, Epidemiology

<br/>

*May 2019*, The Hong Kong Polytechnic University, Faculty of Applied Science and Textiles, HK

**Bachelor of Science in Engineering Physics**

**Selected Courses**: Statistics, Simulation, Time Series Analysis, High Dimensional Data Analysis, Decision Analysis

<br/>

*Aug. - Dec. 2017*, North Carolina State University, College of Sciences, North Carolina, NC, US 

**Student Exchange Program**

**Selected Courses**: Statistics Programming in SAS, Scientific Computing with Python, Statistical Inference & Regression

<br/>

## Working Experience 

*May - Aug. 2019*, **AI Product Manager Intern** (Medical Treatment & Healthcare Group) 

[Ping-An Technology (Shen Zhen) Co., Ltd.](https://tech.pingan.com), Guang Dong, CN 

Accomplishments:

* Studied and searched for latest AI techniques and machine learning models with technical teams

* Designed innovative products with AI techniques in assisting prevention, diagnosis, and treatment of diseases

* Collected and analyzed data from various sources and used SWOT and PEST methods to explore product availability

* Assisted in projects including ‘COPD e-platform for hierarchical diagnosis & treatment’, ‘National health accounts with AI techniques’, ‘Knowledge graph construction for precision medicine’ through data analyses and product design

<br/>

## Academic Research Projects

*May - Aug. 2018*, **Research Intern** 

Johns Hopkins University, Department of Biostatistics, MD, US 

Project: *Inverse Odds Ratio-Weighted (IORW) Estimation for Causal Mediation Analysis*

Supervisor: [Dr. Ni Zhao](http://biostat.jhsph.edu/~nzhao)

Accomplishments:

* Conducted theoretical study on the IORW estimation method in mediation analysis on continuous and binomial cases

* Applied the approach into mediation models and conducted comprehensive simulations with real data in genomics

* Developed more effective modifications to this method using LASSO when dealing with high-dimensional data

<br/>

*Jan. - May 2018*, **Research Assistant**

The Hong Kong Polytechnic University, Department of Applied Mathematics, HK 

Project: *Mathematical Modeling and Prediction for Pneumonia and Influenza (P&I) Mortality*

Supervisor: [Dr. Daihai He](https://www.polyu.edu.hk/ama/people/detail/20/)

Accomplishments:

* Collected, processed and analyzed P&I mortality data and environmental indicators in Hong Kong from 1998 to 2016

* Applied latest machine learning method called ‘boost regression tree model’ in modeling of P&I mortality

* Obtained 95% prediction power in the project which was much better than other current models in P&I mortality studies

<br/>

## Selected Course Projects

*Sep. 2018 - May 2019*

The Hong Kong Polytechnic University, Department of Applied Physics, HK

Capstone Project: **Artificial Neural Network for Molecular Dynamic Simulation**

Supervisor: [Dr. Onofrio Nicolas](http://begbi.alwaysdata.net/index.php)

Accomplishments:

* Created ‘fingerprints’ as data representations for each molecular in data training to improve efficiency

* Built a feed-forward neural network using Python to obtain molecular force given their positions

* Optimized the network and made the error rate less than 5% to be comparable with the most precise quantum method

<br/>

## Techniques and Skills

**Programming Language**:  R, Python, SQL, SAS, C++, C, Git, Tableau, Spark, Microsoft Office

**Software**: Tableau, Microsoft Office

**Language**: Fluent in English

<br/>

## Leadership and Volunteers

*Jan. 2020 - Dec. 2020*, **President**

Career China Club, Mailman School of Public Health, Columbia University

<br/>
*Sep. 2019 - May 2020*, **Wellness Ambassador**

Office of University Life, Columbia University

<br/>
*May 2016 - May 2017*, **Vice President**

The Chinese Mainland Students’ Association, Hong Kong Polytechnic University 

<br/>
*Jun. - Jul. 2016*, **Volunteer**

Voluntary Service in Rural Farms, Sichuan Province, China

<br/>

## Awards and Funds

*Aug. 2018*

Reaching Out Award, HKSAR Government Scholarship

<br/>

*May 2018*

Undergraduate Research Fund, Hong Kong Polytechnic University
