---
title: "My dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
```

Column {data-width=600}
-----------------------------------------------------------------------

### Chart A: Number of items ordered in each aisle with more than 10000 items ordered

```{r}
data("instacart")

instacart %>% 
  count(aisle, name = 'number_of_items_ordered') %>%
  mutate(aisle = fct_reorder(aisle, number_of_items_ordered)) %>% 
  filter(number_of_items_ordered > 10000) %>%
  plot_ly(
    x = ~number_of_items_ordered, y = ~aisle, color = ~aisle, colors = "BrBG", type = 'bar') %>%
  layout(
    xaxis = list(title = "Number of items ordered"),
    yaxis = list(title = "Aisle names"),
    legend = list(orientation = 'h')
  )
```

Column {data-width=400}
-----------------------------------------------------------------------

### Chart B: Number of purchases of fresh vegetables on each day of week

```{r}
instacart %>% 
  mutate(
    order_dow = case_when(
      order_dow == '0' ~ 'Sunday',
      order_dow == '1' ~ 'Monday',
      order_dow == '2' ~ 'Tuesday',
      order_dow == '3' ~ 'Wednesday',
      order_dow == '4' ~ 'Thursday',
      order_dow == '5' ~ 'Friday',
      order_dow == '6' ~ 'Saturday',
    ),
    order_dow = factor(order_dow, levels = c('Sunday', 'Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday'))
  ) %>% 
  filter(aisle == 'fresh vegetables') %>% 
  count(order_dow, name = 'day_of_week') %>% 
  plot_ly(
    x = ~order_dow,  y = ~day_of_week, type = 'scatter', mode = 'lines+markers') %>%
  layout(
    xaxis = list(title = "Day of week"),
    yaxis = list(title = "Number of purchase"),
    legend = list(orientation = 'h')
  )
```

### Chart C: Order hour of fresh vegetables on each day of week

```{r}
instacart %>% 
  mutate(
    order_dow = case_when(
      order_dow == '0' ~ 'Sunday',
      order_dow == '1' ~ 'Monday',
      order_dow == '2' ~ 'Tuesday',
      order_dow == '3' ~ 'Wednesday',
      order_dow == '4' ~ 'Thursday',
      order_dow == '5' ~ 'Friday',
      order_dow == '6' ~ 'Saturday',
    )
  ) %>% 
  filter(aisle == 'fresh vegetables') %>% 
  plot_ly(
    y = ~order_hour_of_day, x = ~order_dow, type = 'box', color = ~order_dow) %>%
  layout(
    xaxis = list(title = "Day of week"),
    yaxis = list(title = "Order hour of day"),
    legend = list(orientation = 'h')
  )
```

