---
title: "List Columns and Iteration"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, message=FALSE, echo=FALSE}
library(tidyverse)

set.seed(1)
```

# List

```{r}
l = list(vec_numeric = 5:8,
         mat         = matrix(1:8, 2, 4),
         vec_logical = c(TRUE, FALSE),
         summary     = summary(rnorm(1000)))
l
```

`For` loop:

```{r}
df = list(
  a = rnorm(20, 3, 1),
  b = rnorm(20, 0, 5),
  c = rnorm(20, 10, .2),
  d = rnorm(20, -3, 1)
)
```

```{r}
mean_and_sd = function(x) {
  
  if (!is.numeric(x)) {
    stop("Argument x should be numeric")
  } else if (length(x) == 1) {
    stop("Cannot be computed for length 1 vectors")
  }
  
  mean_x = mean(x)
  sd_x = sd(x)

  tibble(
    mean = mean_x, 
    sd = sd_x
  )
}
```

```{r}
mean_and_sd(df[[1]])
```

```{r}
output = vector("list", length = 4)

for (i in 1:4) {
  output[[i]] = mean_and_sd(df[[i]])
}
```

`Map` function:

```{r}
output = map(df, mean_and_sd)

output_median = map(df, median)

output_median_1 = map_dbl(df, median)

output_median_2 = map_dfr(df, median)
```

```{r}
# more specific
output = map(df, ~mean_and_sd(.x))
```

## An Example

```{r}
library(rvest)
## Loading required package: xml2
## 
## Attaching package: 'rvest'
## The following object is masked from 'package:purrr':
## 
##     pluck
## The following object is masked from 'package:readr':
## 
##     guess_encoding

read_page_reviews = function(url) {
  
  h = read_html(url)
  
  title = h %>%
    html_nodes("#cm_cr-review_list .review-title") %>%
    html_text()
  
  stars = h %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("\\d") %>%
    as.numeric()
  
  text = h %>%
    html_nodes(".review-data:nth-child(5)") %>%
    html_text()
  
  data_frame(title, stars, text)
}


url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_urls = str_c(url_base, 1:5)

dynamite_reviews = map_df(vec_urls, read_page_reviews)
```


# List columns

```{r, message=FALSE}
weather = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2016-01-01",
    date_max = "2016-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())


weather_nest = 
  weather %>% 
  nest(data = date:tmin)

weather_nest
```

```{r}
weather_nest %>% 
  pull(data) %>% 
  .[[1]]

weather_nest$data[[1]]

weather_nest %>% 
  unnest()
```

## Operations on lisnt columns

```{r}
central_park_df = 
  weather_nest$data[[1]]

lm(tmax ~ tmin, data = central_park_df)


lm(tmax ~ tmin, data = weather_nest$data[[1]])


# into map statement

weather_lm = function(df){
  lm(tmax ~ tmin, data = df)
}

output = map(weather_nest$data, weather_lm)
```

```{r}
weather_nest %>% 
  mutate(
    lin_model = map(data, weather_lm)
  )
```
