---
title: "Linear Regression"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r, message=FALSE, echo=FALSE}
library(tidyverse)
library(p8105.datasets)

set.seed(1)
```

## Model Fitting

```{r}
data("nyc_airbnb")

nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(stars = review_scores_location / 2) %>% 
  rename(
    boro = neighbourhood_group,
    neighborhood = neighbourhood) %>% 
  filter(boro != "Staten Island") %>% 
  dplyr::select(price, stars, boro, neighborhood, room_type)
```

Fit the first linear model:

```{r}
fit = lm(price ~ stars + boro, data = nyc_airbnb)

summary(fit)
coef(fit)
```

Tidy the results:

```{r}
fit %>% 
  broom::tidy() %>% 
  mutate(
    term = str_replace(term, "boro", "Boro:") 
  ) %>% 
  knitr::kable()
```

Take a look at factors...

```{r}
nyc_airbnb = 
  nyc_airbnb %>% 
  mutate(
    boro = fct_infreq(boro),  # reorder factor levels based on their frequencies
    room_type = fct_infreq(room_type))

fit = lm(price ~ stars + boro, data = nyc_airbnb)
fit %>% broom::glance()
```

## Diagnostics

```{r}
modelr::add_residuals(nyc_airbnb, fit) %>% 
  ggplot(aes(x = boro, y = resid)) + 
  geom_violin() +
  ylim(-500, 500)
```

```{r}
nyc_airbnb %>% 
  modelr::add_residuals(fit) %>% 
  ggplot(aes(x = stars, y = resid)) + 
  geom_point() +
  ylim(-500, 500)
```

```{r}
modelr::add_predictions(nyc_airbnb, fit)
```

## Nesting

```{r}
nyc_airbnb %>% 
  lm(price ~ stars * boro + room_type * boro, data = .) %>% 
  broom::tidy() %>% 
  knitr::kable(digits = 3)
```

```{r}
nest_lm_res =
  nyc_airbnb %>% 
  nest(data = -boro) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  dplyr::select(-data) %>% 
  unnest(models)
```

```{r}
manhattan_airbnb =
  nyc_airbnb %>% 
  filter(boro == "Manhattan")

manhattan_nest_lm_res =
  manhattan_airbnb %>% 
  nest(data = -neighborhood) %>% 
  mutate(models = map(data, ~lm(price ~ stars + room_type, data = .x)),
         models = map(models, broom::tidy)) %>% 
  dplyr::select(-data) %>% 
  unnest(models)

manhattan_nest_lm_res %>% 
  filter(str_detect(term, "room_type")) %>% 
  ggplot(aes(x = neighborhood, y = estimate)) + 
  geom_point() + 
  facet_wrap(~term) + 
  theme(axis.text.x = element_text(angle = 80, hjust = 1))
```

